remote_theme: pages-themes/leap-day@v0.2.0
plugins:
  - jekyll-remote-theme
title: Mole Mining Guide - Star Citizen Universe
description: A quick guide to efficient mining with the MOLE in Star Citizen, covering key mechanics, loadouts, and tips.
show_downloads: false