remote_theme: pages-themes/leap-day@v0.2.0
plugins:
  - jekyll-remote-theme
title: Mole Mining Guide - Star Citizen Universe
description: A guide that explains why things work, not just what to do.
show_downloads: false